<?php

namespace common\widgets\NotificationWidget;

use common\models\Trip;
use yii\base\Widget;

class NotificationWidget extends Widget {

    public function run() {
        // Register AssetBundle
        $bundle = NotificationWidgetAssets::register($this->getView());
        $notifications = $this->getNotifications();
        $this->view->params['notifications'] = $notifications;
        return $this->render('_notification');
    }

    private function getNotifications() {
        $return_value = [];

        $incompleteTrips = Trip::getIncompleteTrips();
        if (count($incompleteTrips) > 0) {
            $return_value['incomplete_trips'] = count($incompleteTrips);
        }
        return $return_value;
    }

    public static function end() {
        return parent::end(); // TODO: Change the autogenerated stub
    }
}