<?php

namespace common\widgets\PaymentInformationsWidget;

use yii\base\Widget;

class PaymentInformationsWidget extends Widget {

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run() {
        PaymentInformationsWidgetAssets::register($this->getView());
        return $this->render('_paymentInformations', []);

    }
}