<?php


namespace common\widgets\MailWidget;


use common\models\Trip;
use yii\base\Widget;

class MailWidget extends Widget {
    public $type = '';
    public $trip_id = null;

    public function init() {
//        echo $this->type.'<br>';
        parent::init();
        if ($this->trip_id != null) {
            $this->view->params['trip_id'] = $this->trip_id;
        }
    }

    public function run() {
        MailWidgetAsset::register($this->getView());
        switch ($this->type) {
            case "tripReport" :
                $this->view->params['trip'] = Trip::find()->where(['id' => $this->trip_id])->one();
                return $this->render('_tripReport', []);
                break;
            default:
                return null;
                break;
        }
    }

    public static function end() {
        return parent::end(); // TODO: Change the autogenerated stub
    }
}